In [1]:


import pandas as pd
import matplotlib.pyplot as plt
import sqlite3 as sql
import random
import os

Reproducible Code of the Datasets and Creation of CSV Files. Data processing is done by Python and Pandas, pushed out into CSV form and finally uploaded into Huawei Cloud GaussDB using Data Admin Service.

In [93]:
greenmark = pd.read_csv("./listing-of-building-energy-performance-data-2020.csv")

In [94]:
greenmark.columns

Index(['buildingname', 'buildingaddress', 'buildingtype',
       'mainbuildingfunction', 'buildingsize', 'yearobtainedtopcsc',
       'greenmarkrating', 'greenmarkyearofaward', 'greenmarkversion',
       'grossfloorarea', 'percentageofairconditionedfloorarea',
       'averagemonthlybuildingoccupancyrate', 'numberofhotelrooms',
       'typeofairconditioningsystem', 'ageofchiller',
       'centralisedairconditioningplantefficiency',
       'yearoflastchillerplantaudithealthcheck', 'percentageusageofled',
       'installationofsolarpv', '2017', '2018', '2019', '2020'],
      dtype='object')

In [95]:
greenmark.dtypes

buildingname                                  object
buildingaddress                               object
buildingtype                                  object
mainbuildingfunction                          object
buildingsize                                  object
yearobtainedtopcsc                             int64
greenmarkrating                               object
greenmarkyearofaward                         float64
greenmarkversion                              object
grossfloorarea                                object
percentageofairconditionedfloorarea           object
averagemonthlybuildingoccupancyrate           object
numberofhotelrooms                           float64
typeofairconditioningsystem                   object
ageofchiller                                 float64
centralisedairconditioningplantefficiency    float64
yearoflastchillerplantaudithealthcheck       float64
percentageusageofled                          object
installationofsolarpv                         object
2017                                         float64
2018                                         float64
2019                                         float64
2020                                         float64
dtype: object

In [96]:
greenmark

,buildingname,buildingaddress,buildingtype,mainbuildingfunction,buildingsize,yearobtainedtopcsc,greenmarkrating,greenmarkyearofaward,greenmarkversion,grossfloorarea,...,typeofairconditioningsystem,ageofchiller,centralisedairconditioningplantefficiency,yearoflastchillerplantaudithealthcheck,percentageusageofled,installationofsolarpv,2017,2018,2019,2020
0,UNITED SQUARE,"101 THOMSON ROAD, SINGAPORE 307591",Commercial Building,Mixed Development,Large,1984,NaN,NaN,NaN,"65,947",...,Water Cooled Chilled Water Plant,12.0,0.68,2019.0,2%,N,281.32,276.83,274.91,250.89
1,HPL HOUSE,"50 CUSCADEN ROAD, SINGAPORE 249724",Commercial Building,Office,Small,1980,NaN,NaN,NaN,"7,372",...,Others,2.0,NaN,NaN,80%,N,277.93,268.76,264.79,216.27
2,GRACE GLOBAL RAFFLES,"137 MARKET STREET, SINGAPORE 048943",Commercial Building,Office,Small,2011,GoldPlus,2010.0,New Building for Non-Residential buildings (ve...,"5,030",...,Others,9.0,NaN,NaN,20%,N,171.16,165.32,165.52,115.42
3,THE GLOBE,"100 CECIL STREET, SINGAPORE 069532",Commercial Building,Office,Small,1993,NaN,NaN,NaN,"5,824",...,Others,0.0,NaN,NaN,30%,N,185.64,168.50,163.46,138.01
4,HIGH STREET PLAZA,"77 HIGH STREET, SINGAPORE 179433",Commercial Building,Office,Small,1975,NaN,NaN,NaN,"10,418",...,Water Cooled Chilled Water Plant,38.0,0.80,2020.0,90%,N,158.37,140.95,149.12,129.54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559,ORCHARD GATEWAY,"277 ORCHARD ROAD, SINGAPORE 238858",Commercial Building,Mixed Development,Large,2014,Platinum,2020.0,New Building for Non-Residential buildings (ve...,"48,324",...,Water Cooled Chilled Water Plant,7.0,NaN,NaN,80%,N,370.82,369.80,369.88,302.62
560,FUNAN,"109 NORTH BRIDGE ROAD, SINGAPORE 179097",Commercial Building,Mixed Development,Large,2019,GoldPlus,2018.0,New Building for Non-Residential buildings (ve...,"80,858",...,Water Cooled Chilled Water Plant,2.0,NaN,NaN,100%,Y,NaN,NaN,208.43,365.25
561,TANJONG KATONG COMPLEX,"845 GEYLANG ROAD, SINGAPORE 400845",Commercial Building,Retail,Large,1983,NaN,NaN,NaN,"18,841",...,Water Cooled Chilled Water Plant,17.0,NaN,NaN,25%,N,233.81,221.81,216.03,144.90
562,VISION EXCHANGE,"2 VENTURE DRIVE, SINGAPORE 608526",Commercial Building,Office,Large,2017,GoldPlus,2016.0,New Building for Non-Residential buildings (ve...,"64,562",...,Water Cooled Chilled Water Plant,3.0,0.59,2019.0,78%,N,66.01,92.36,125.91,121.20
563,TEXTILE CENTRE,"200 JALAN SULTAN, SINGAPORE 199018",Commercial Building,Retail,Large,1977,NaN,NaN,NaN,"47,750",...,Water Cooled Chilled Water Plant,5.0,NaN,NaN,20%,N,147.40,138.09,148.09,123.41

In [97]:
greenmark.dtypes

buildingname                                  object
buildingaddress                               object
buildingtype                                  object
mainbuildingfunction                          object
buildingsize                                  object
yearobtainedtopcsc                             int64
greenmarkrating                               object
greenmarkyearofaward                         float64
greenmarkversion                              object
grossfloorarea                                object
percentageofairconditionedfloorarea           object
averagemonthlybuildingoccupancyrate           object
numberofhotelrooms                           float64
typeofairconditioningsystem                   object
ageofchiller                                 float64
centralisedairconditioningplantefficiency    float64
yearoflastchillerplantaudithealthcheck       float64
percentageusageofled                          object
installationofsolarpv                         object
2017                                         float64
2018                                         float64
2019                                         float64
2020                                         float64
dtype: object

In [98]:
greenmark['greenmarkrating'] = greenmark['greenmarkrating'].fillna("Uncertified")
greenmark['greenmarkyearofaward'] = greenmark['greenmarkyearofaward'].fillna(0)

In [99]:
def retrievepostalcode(address): #Retrieving postal code from address
    return int(address[-6:])

def greenmarkscore(cert): #Dummy data creation
    if cert == 'Uncertified':
        return random.randint(1, 40)
    elif cert == 'Certified' or cert == 'Legislated':
        return random.randint(41, 60)
    elif cert == 'Gold':
        return random.randint(61, 70)
    elif cert == 'GoldPlus':
        return random.randint(71, 80)
    else:
        return random.randint(81, 100)

In [100]:
greenmark['postalcode'] = greenmark['buildingaddress'].apply(retrievepostalcode)
greenmark['greenmarkscore'] = greenmark['greenmarkrating'].apply(greenmarkscore)

In [101]:
greenmark

,buildingname,buildingaddress,buildingtype,mainbuildingfunction,buildingsize,yearobtainedtopcsc,greenmarkrating,greenmarkyearofaward,greenmarkversion,grossfloorarea,...,centralisedairconditioningplantefficiency,yearoflastchillerplantaudithealthcheck,percentageusageofled,installationofsolarpv,2017,2018,2019,2020,postalcode,greenmarkscore
0,UNITED SQUARE,"101 THOMSON ROAD, SINGAPORE 307591",Commercial Building,Mixed Development,Large,1984,Uncertified,0.0,NaN,"65,947",...,0.68,2019.0,2%,N,281.32,276.83,274.91,250.89,307591,38
1,HPL HOUSE,"50 CUSCADEN ROAD, SINGAPORE 249724",Commercial Building,Office,Small,1980,Uncertified,0.0,NaN,"7,372",...,NaN,NaN,80%,N,277.93,268.76,264.79,216.27,249724,32
2,GRACE GLOBAL RAFFLES,"137 MARKET STREET, SINGAPORE 048943",Commercial Building,Office,Small,2011,GoldPlus,2010.0,New Building for Non-Residential buildings (ve...,"5,030",...,NaN,NaN,20%,N,171.16,165.32,165.52,115.42,48943,74
3,THE GLOBE,"100 CECIL STREET, SINGAPORE 069532",Commercial Building,Office,Small,1993,Uncertified,0.0,NaN,"5,824",...,NaN,NaN,30%,N,185.64,168.50,163.46,138.01,69532,27
4,HIGH STREET PLAZA,"77 HIGH STREET, SINGAPORE 179433",Commercial Building,Office,Small,1975,Uncertified,0.0,NaN,"10,418",...,0.80,2020.0,90%,N,158.37,140.95,149.12,129.54,179433,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559,ORCHARD GATEWAY,"277 ORCHARD ROAD, SINGAPORE 238858",Commercial Building,Mixed Development,Large,2014,Platinum,2020.0,New Building for Non-Residential buildings (ve...,"48,324",...,NaN,NaN,80%,N,370.82,369.80,369.88,302.62,238858,84
560,FUNAN,"109 NORTH BRIDGE ROAD, SINGAPORE 179097",Commercial Building,Mixed Development,Large,2019,GoldPlus,2018.0,New Building for Non-Residential buildings (ve...,"80,858",...,NaN,NaN,100%,Y,NaN,NaN,208.43,365.25,179097,71
561,TANJONG KATONG COMPLEX,"845 GEYLANG ROAD, SINGAPORE 400845",Commercial Building,Retail,Large,1983,Uncertified,0.0,NaN,"18,841",...,NaN,NaN,25%,N,233.81,221.81,216.03,144.90,400845,24
562,VISION EXCHANGE,"2 VENTURE DRIVE, SINGAPORE 608526",Commercial Building,Office,Large,2017,GoldPlus,2016.0,New Building for Non-Residential buildings (ve...,"64,562",...,0.59,2019.0,78%,N,66.01,92.36,125.91,121.20,608526,76
563,TEXTILE CENTRE,"200 JALAN SULTAN, SINGAPORE 199018",Commercial Building,Retail,Large,1977,Uncertified,0.0,NaN,"47,750",...,NaN,NaN,20%,N,147.40,138.09,148.09,123.41,199018,20

In [102]:
meanCarbonEmissions = greenmark.iloc[:,-5:-2].mean(axis = 1)

In [103]:
buildings = greenmark.filter(['postalcode', 'buildingaddress', 'buildingname', 'mainbuildingfunction'])
buildings['latitude'] = ""
buildings['longitude'] = ""

In [104]:
buildings

,postalcode,buildingaddress,buildingname,mainbuildingfunction,latitude,longitude
0,307591,"101 THOMSON ROAD, SINGAPORE 307591",UNITED SQUARE,Mixed Development,,
1,249724,"50 CUSCADEN ROAD, SINGAPORE 249724",HPL HOUSE,Office,,
2,48943,"137 MARKET STREET, SINGAPORE 048943",GRACE GLOBAL RAFFLES,Office,,
3,69532,"100 CECIL STREET, SINGAPORE 069532",THE GLOBE,Office,,
4,179433,"77 HIGH STREET, SINGAPORE 179433",HIGH STREET PLAZA,Office,,
...,...,...,...,...,...,...
559,238858,"277 ORCHARD ROAD, SINGAPORE 238858",ORCHARD GATEWAY,Mixed Development,,
560,179097,"109 NORTH BRIDGE ROAD, SINGAPORE 179097",FUNAN,Mixed Development,,
561,400845,"845 GEYLANG ROAD, SINGAPORE 400845",TANJONG KATONG COMPLEX,Retail,,
562,608526,"2 VENTURE DRIVE, SINGAPORE 608526",VISION EXCHANGE,Office,,
563,199018,"200 JALAN SULTAN, SINGAPORE 199018",TEXTILE CENTRE,Retail,,

In [105]:
building_details = greenmark.filter(['postalcode', 'greenmarkscore'])
building_details['notable_qualities'] = ""
building_details['other_awards'] = ""
building_details['carbon_emissions'] = greenmark.iloc[:,-5:-2].mean(axis = 1).round(3)

In [106]:
building_details

,postalcode,greenmarkscore,notable_qualities,other_awards,carbon_emissions
0,307591,38,,,267.543
1,249724,32,,,249.940
2,48943,74,,,148.753
3,69532,27,,,156.657
4,179433,33,,,139.870
...,...,...,...,...,...
559,238858,84,,,347.433
560,179097,71,,,286.840
561,400845,24,,,194.247
562,608526,76,,,113.157
563,199018,20,,,136.530

In [107]:
buildings.to_csv(os.getcwd() + r'buildings.csv',index = False)

In [108]:
building_details.to_csv(os.getcwd() + r'buildingdetails.csv',index = False)

In [109]:
buildings.dtypes

postalcode               int64
buildingaddress         object
buildingname            object
mainbuildingfunction    object
latitude                object
longitude               object
dtype: object